"use strict";
const test=require('node:test'),assert=require('node:assert/strict'),{spawn}=require('node:child_process'),fs=require('node:fs'),path=require('node:path');
const base=path.resolve(__dirname,'../..'),bin=path.join(base,'bin/kdna-studio.js'),root=path.resolve(process.env.STUDIO_TEST_ARTIFACT_ROOT || path.join(__dirname,'.artifacts',String(process.pid)));fs.mkdirSync(root,{recursive:true});let serial=0;
function run(argv,label){return new Promise((resolve,reject)=>{const start=new Date().toISOString(),p=spawn(process.execPath,[bin,...argv],{cwd:base,stdio:['pipe','pipe','pipe','pipe']});let out='',err='',partial='';const events=[];const record={pid:p.pid,start,argv};p.stdout.on('data',b=>{out+=b;partial+=b;let k;while((k=partial.indexOf('\n'))>=0){const line=partial.slice(0,k);partial=partial.slice(k+1);try{events.push(JSON.parse(line));}catch{}}});p.stderr.on('data',b=>err+=b);p.stdin.on('error',()=>{});p.stdio[3].on('error',()=>{});p.on('error',reject);p.on('close',(code,signal)=>{clearTimeout(timer);record.end=new Date().toISOString();record.exit=code;record.signal=signal;fs.writeFileSync(path.join(root,label+'.execution.json'),JSON.stringify({...record,stdout:out,stderr:err,events},null,2),{flag:'wx'});resolve({...record,out,err,events});});const timer=setTimeout(()=>{p.kill('SIGTERM');},10000);resolveOnEvent(p,events);function resolveOnEvent(){};p._eventsForTest=events;p._recordForTest=record;run.last=p;});}
async function create(kind,{extra=false,closeProvider=false}={}){const label=kind+'-'+(++serial),folder=path.join(root,label);fs.mkdirSync(folder);const source=path.join(folder,'material.txt');fs.writeFileSync(source,'PRIVATE_CLI_SOURCE_TEXT_'+label);const delegation=path.join(folder,'delegation.json');fs.writeFileSync(delegation,JSON.stringify({coordinate:'fixture:authorized-local-agent',statement:'Synthetic provider execution only, no real editorial acceptance.'}));const bundle=path.join(folder,'bundle');const argv=['session','--out',bundle,'--text',source,'--synthetic-fixture',...(kind==='agent'?['--agent-adoption-fd','3','--delegation-record',delegation]:['--human-fd','3'])];const promise=run(argv,label);const p=run.last;let buffer='';const send=(id,op,data)=>p.stdin.write(JSON.stringify({id,op,data})+'\n');const alternative={localKey:'preserve',title:'Observed signal',subject:'A synthetic observation',scope:'Missing observations only',statement:'Retain unknown when an observation is absent.',formationRule:{conditions:[]},rationale:'No observation does not establish a negative finding.',materials:[1],method:{method:{term:'evidence-classification'},components:[{localKey:'states',type:'taxonomy',content:{items:[{key:'known',title:'Observed é',meaning:'Input observation is present.'},{key:'unknown',title:'Unobserved e\u0301',meaning:'Input observation is absent.'}],broader:[]}}],bindings:[{componentLocalKey:'states',role:'input-items'}]}};
 p.stdout.on('data',b=>{buffer+=b;let k;while((k=buffer.indexOf('\n'))>=0){const raw=buffer.slice(0,k);buffer=buffer.slice(k+1);let e;try{e=JSON.parse(raw);}catch{continue;}
 if(e.event==='ready')send('brief','brief',{title:'CLI component fixture',scope:'Independent process synthetic integration.'});
 else if(e.id==='brief')send('proposal','propose',{localKey:'signal',alternatives:[alternative,{...alternative,localKey:'infer',statement:'Treat missing input as a negative.'}],...(extra?{unexpected:'must reject'}:{})});
 else if(e.id==='proposal'){send('select-review','review',{});if(closeProvider)p.stdio[3].end();else p.stdio[3].write('Select the preserve alternative.\n');}
 else if(e.event==='adoption_reply')send('interpret-'+e.replyTo,'interpret',{replyTo:e.replyTo,kind:e.review.preview?'confirm':'select',...(e.review.preview?{}:{choices:[{judgmentLocalKey:'signal',alternativeLocalKey:'preserve'}]})});
 else if(e.id==='select-review')send('preview','preview',{});
 else if(e.id==='preview'){send('confirm-review','review',{});p.stdio[3].write('Confirm this exact current preview.\n');}
 else if(e.id==='confirm-review')send('export','export',{});
 }});
 return {result:await promise,bundle,folder};}
for(const kind of ['agent','human'])test('real CLI current packed Studio save/readback '+kind,async()=>{const {result,bundle}=await create(kind);assert.equal(result.exit,0,result.err);const completed=JSON.parse(fs.readFileSync(path.join(bundle,'verification.json')));assert.equal(completed.status,'accepted_with_live_context');assert.equal(completed.adoption_kind,kind==='agent'?'delegated_agent_editorial':'human_claim_unverified');assert.equal(JSON.parse(fs.readFileSync(path.join(bundle,'complete.json'))).version,2);const bytes=fs.readFileSync(path.join(bundle,'asset.kdna'));assert.equal(bytes.includes(Buffer.from('PRIVATE_CLI_SOURCE_TEXT_')),false);const evidence=JSON.parse(fs.readFileSync(path.join(bundle,'creation-evidence.json')));assert.equal(evidence.decision.actual_reply.response.role,kind);const verify=await run(['verify','--bundle',bundle],kind+'-verify');assert.equal(verify.exit,0,verify.err);assert.equal(verify.events[0].live_context,'unavailable');assert.equal(verify.events[0].creation_accepted,'not_evaluated');const read=await run(['read','--bundle',bundle,'--allow-read','--judgment','1','--budget','1048576'],kind+'-read');assert.equal(read.exit,0,read.err);assert.equal(read.events[0].envelope.status,'ready');assert.ok(read.events[0].envelope.content.closure.find(n=>n.role==='method').value.component_interpretations.length===1);});
test('CLI rejects unknown group data before export',async()=>{const {result,bundle}=await create('agent',{extra:true});assert.equal(result.exit,2);assert.match(result.err,/CLI_COMPONENT_INPUT_INVALID/);assert.equal(fs.existsSync(bundle),false);});
test('CLI closes after adoption fd EOF without output bundle',async()=>{const {result,bundle}=await create('agent',{closeProvider:true});assert.equal(result.exit,2);assert.match(result.err,/CLI_HUMAN_CHANNEL_CLOSED/);assert.equal(fs.existsSync(bundle),false);});
test('Agent channel requires explicit delegation and cannot share human flag',async()=>{const result=await run(['session','--out',path.join(root,'never'),'--agent-adoption-fd','3'],'missing-delegation');assert.equal(result.exit,2);assert.match(result.err,/CLI_ADOPTION_OPTIONS_INVALID/);});
